name: vidclone
description: With permission from a user, downloads YouTube videos as they're released.
# version: 1.0.0
# homepage: https://www.puffinlabs.me

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  googleapis: any
  googleapis_auth: any
  http: any

dev_dependencies:
  pedantic: ^1.8.0
